# Generated by Django 2.1.7 on 2019-02-16 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vertion1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Chinese_Name', models.CharField(max_length=30)),
                ('Sex', models.CharField(choices=[('f', 'female'), ('m', 'male')], max_length=1)),
                ('Nationality', models.CharField(max_length=30)),
                ('email', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vertion1.User')),
            ],
        ),
    ]
