# Generated by Django 2.1.7 on 2019-02-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertion1', '0002_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='Date_Of_Birth',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Email',
            field=models.EmailField(default='null', max_length=254),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Emergency_Name',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Emergency_Phone',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Emergency_Relationship',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Emergency_email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Health_Condition',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Highest_Education',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Mail_Address',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Mail_City',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Mail_Country',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Mail_Phone',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Mail_Postcode',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Mail_Recipient',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Mather_Tongue',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Name_Of_Institution',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Name_Of_Sponsor',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Phone_Number',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Place_of_Birth',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Religion',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Sponsor_Email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Sponsor_Phone',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user_info',
            name='Sponsor_Relationship',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='Chinese_Name',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='First_Name',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='Last_Name',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='Nationality',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='Sex',
            field=models.CharField(choices=[('f', 'female'), ('m', 'male')], default='null', max_length=1),
        ),
    ]
